In [1]:
import numpy as np
import sympy

In [2]:
def thinking_into_3dv(x_0, y_0, x_1, y_1):
    
    x_0 = np.array(x_0, dtype=np.float64)
    x_1 = np.array(x_1, dtype=np.float64)
    y_0 = np.array(y_0, dtype=np.float64)
    y_1 = np.array(y_1, dtype=np.float64)

    x_0 = x_0.reshape(3, 1)
    x_1 = x_1.reshape(3, 1)
    y_0 = y_0.reshape(3, 1)
    y_1 = y_1.reshape(3, 1)

    u_1 = x_1 - (np.dot(x_0.T, x_1) / np.dot(x_0.T, x_0)) * x_0
    v_1 = y_1 - (np.dot(y_0.T, y_1) / np.dot(y_0.T, y_0)) * y_0

    sympy.var('x, y, z')

    fx = x_0[0][0]*x + x_0[1][0]*y + x_0[2][0]*z
    gx = x_1[0][0]*x + x_1[1][0]*y + x_1[2][0]*z
    hx = x**2 + y**2 + z**2 -1

    s = sympy.solve([fx, gx, hx], [x, y, z])

    sympy.var('a, b, c')

    fx = y_0[0][0]*a + y_0[1][0]*b + y_0[2][0]*c
    gx = y_1[0][0]*a + y_1[1][0]*b + y_1[2][0]*c
    hx = a**2 + b**2 + c**2 -1

    r = sympy.solve([fx, gx, hx], [a, b, c])

    n = np.array([s[1][0], s[1][1], s[1][2]], dtype=np.float64).reshape(3, 1)
    m = np.array([r[0][0], r[0][1], r[0][2]], dtype=np.float64).reshape(3, 1)

    q_1 = np.dot(y_0, x_0.T) * 1/np.dot(x_0.T, x_0) 
    q_2 = np.dot(v_1, u_1.T) * 1/np.dot(u_1.T, u_1) 
    q_3 = np.dot(m, n.T) 

    Q = q_1 + q_2 + q_3

    return Q

In [3]:
# change number (full rank)
thinking_into_3dv([1, 2, 3], [3, 2, 1], [4, 5, 6], [6, 5, 4])

array([[-0.33333333,  0.66666667,  0.66666667],
       [ 0.66666667, -0.33333333,  0.66666667],
       [ 0.66666667,  0.66666667, -0.33333333]])

In [4]:
# change number (full rank)
thinking_into_3dv([1, 2, 3], [3, 2, 1], [19, 33, 39], [39, 33, 19])

array([[-0.26582278,  0.2278481 ,  0.93670886],
       [ 0.95696203,  0.17974684,  0.2278481 ],
       [-0.1164557 ,  0.95696203, -0.26582278]])

In [5]:
# change number (full rank)
thinking_into_3dv([1, 2, 3], [3, 2, 1], [1, 8, 9], [9, 8, 1])

array([[ 5.55111512e-17, -5.55111512e-17,  1.00000000e+00],
       [-5.55111512e-17,  1.00000000e+00, -5.55111512e-17],
       [ 1.00000000e+00, -5.55111512e-17,  5.55111512e-17]])

In [6]:
# scalling number
thinking_into_3dv([1, 2, 3], [2, 4, 6], [4, 5, 6], [8, 10, 12])

array([[ 1.50000000e+00,  1.00000000e+00, -5.00000000e-01],
       [ 1.00000000e+00,  1.11022302e-16,  1.00000000e+00],
       [-5.00000000e-01,  1.00000000e+00,  1.50000000e+00]])